# require_relative 'momentum_api/api/params'
# require_relative 'momentum_api/error'
require_relative 'momentum_api/version'
require_relative 'momentum_api/discourse'
require_relative 'momentum_api/schedule'
require_relative 'momentum_api/man'
require_relative 'momentum_api/api/messages'
require_relative 'momentum_api/api/polls'
require_relative 'momentum_api/api/watch_category'
require_relative 'momentum_api/api/watch_group'
require_relative 'momentum_api/api/preferences'
require_relative 'momentum_api/api/activity'
require_relative 'momentum_api/api/activity_group'
require_relative 'momentum_api/api/downgrade_trust'

